{% set name = "aligator" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 48733ccef976435ffd3819297d3181ec9ad945f06c90e4420bc5887f9e9f70b5

build:
  number: 0
  # Windows build has to be fixed
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja  # [win]
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - proxsuite-nlp
    - eigen
    - eigenpy
    - libboost-devel
    - libboost-python-devel
    - pinocchio
    # Crocoddyl package is not available on Windows, aarch64 and ppc64le
    - crocoddyl  # [not win and not aarch64 and not ppc64le]
    - python
    - numpy
    - matplotlib-base
    - example-robot-data
    - fmt
  run:
    - eigen
    - eigenpy
    - python
    - matplotlib-base
    - typed-argument-parser

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_PREFIX%\bin\{{ name }}.dll exit 1  # [win]
  imports:
    - aligator

about:
  home: https://github.com/simple-robotics/aligator
  summary: A versatile and efficient framework for constrained trajectory optimization.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/simple-robotics/aligator

extra:
  recipe-maintainers:
    - ymontmarin
    - fabinsch
    - olivier-roussel
    - jcarpent
    - jorisv
    - ManifoldFR
